#pragma config(Sensor, in2,    spin_angle,     sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    push_angle,     sensorPotentiometer)
#pragma config(Sensor, in6,    ,               sensorPotentiometer)
#pragma config(Sensor, in8,    lift_angle,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  right_encoder,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  alpha,          sensorDigitalIn)
#pragma config(Sensor, dgtl4,  beta,           sensorDigitalIn)
#pragma config(Sensor, dgtl5,  gamma,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, left_encoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           arm_reach,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           right_back_wheel, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           right_front_wheel, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           jack_left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           crank_left,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           crank_right,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           jack_right,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           left_front_wheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           left_back_wheel, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          catching,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "auto_included.c"


void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	eight_one_blue();
  //four_three_blue();
  //clearDebugStream();
  //short_break_blue();
	while(true)
	{delay(10);}
	//int auto_select = SensorValue[alpha]*4 + SensorValue[beta]*2 + SensorValue[gamma]*1;

	//switch(auto_select)
	//{
	//  case 0 :
	//    eight_one_blue();
	//    break;
	//  case 1 :
	//    eight_one_red();
	//    break;
	//  case 2 :
	//    four_three_blue();
	//    break;
	//  case 3 :
	//    four_three_red();
	//    break;
	//  default:
	//    break;
	//}
}

task usercontrol()
{
	clearDebugStream();
	user_control();
}
